<a href="https://colab.research.google.com/github/Aks-20/AI-ML/blob/main/AkshatGupta22csu312.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [16]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,2])
c=a+b
print(c)
c.sort()
print(c)

[3 5 7 6]
[3 5 6 7]


In [20]:
d=np.array([(1,2,3),(4,5,6)])
e=np.array([(7,3,1),(14,15,36)])
print(d+e)
print(e)


[[ 8  5  4]
 [18 20 42]]
[[ 7  3  1]
 [14 15 36]]


In [23]:
g=np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
i=np.arange(10,25,5)
i

array([10, 15, 20])

In [27]:
k=np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [28]:
l=np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [29]:
n=np.random.random((2,2))
n

array([[0.6746212 , 0.34822159],
       [0.01553484, 0.75974107]])